driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.12.2

platforms:
  - name: ubuntu-12.04
    run_list:
      - apt::default
      - teamcity::java
  - name: centos-6.4
    run_list:
      - yum::default
      - teamcity::java

suites:
- name: default
  includes:
    - ubuntu-12.04
  run_list:
  - recipe[minitest-handler]
  - recipe[teamcity_server_test]
